### ISSUE TITLE
"invitatoř"

### ISSUE THREAD

**Issue by igneus** [breviar-sk/Liturgia-hodin-online#2]
Mezi [překladovými texty pro androidí aplikaci](https://github.com/breviar-sk/Liturgia-hodin-online/blob/master/android/res/values-cs/strings.xml) jsem narazil na slovo **"invitatoř"** jako označení té části oficia, která se v latinském pokoncilním breviáři jmenuje "invitatorium" a v české Denní modlitbě církve "uvedení do první modlitby dne". Na jednu stranu se mi to slovo moc líbí (v mateřskojazyčných liturgických knihách českých utrakvistů mu dělaly společnost další podobně rozkošné termíny jako "responsoř" nebo "veršík"), na druhou stranu působí rušivě, protože nepatří do stejné vrstvy jazyka jako zbytek textů a rubrik breviáře: "responsoř" a "invitatoř" dnes mezi sebou říkají nanejvýš odborníci na utrakvistickou liturgii. Počeštění latinských slov končících "-orium" změnou na "-oř" se dávno nepoužívá.

Předpokládám, že jednoslovné pojmenování odchylující se od názvosloví českých liturgických knih bylo zvoleno z důvodů místa, aby se to i na malých displejích vešlo na jeden řádek. V tom případě navrhuji "invitatorium".

Dále jsem v tomtéž souboru narazil na slovakismus **"Co je nové"**. Přirozeněji český ekvivalent je "Co je nového", popř. "Novinky", "Nově přidáno" apod.

**Comment by breviar-sk** [comment]
+!
Jakube,

díky za postřehy. Opraveno: Inivtatoř –> Uvedení. “Co je nové” –> “Co je nového”.

Juraj V.

From: Jakub Pavlík 
Sent: Wednesday, August 31, 2016 6:54 PM
To: breviar-sk/Liturgia-hodin-online 
Subject: [breviar-sk/Liturgia-hodin-online] "invitatoř" (#2)

Mezi překladovými texty pro androidí aplikaci jsem narazil na slovo "invitatoř" jako označení té části oficia, která se v latinském pokoncilním breviáři jmenuje "invitatorium" a v české Denní modlitbě církve "uvedení do první modlitby dne". Na jednu stranu se mi to slovo moc líbí (v mateřskojazyčných liturgických knihách českých utrakvistů mu dělaly společnost další podobně rozkošné termíny jako "responsoř" nebo "veršík"), na druhou stranu působí rušivě, protože nepatří do stejné vrstvy jazyka jako zbytek textů a rubrik breviáře: "responsoř" a "invitatoř" dnes mezi sebou říkají nanejvýš odborníci na utrakvistickou liturgii. Počeštění latinských slov končících "-orium" změnou na "-oř" se dávno nepoužívá.

Předpokládám, že jednoslovné pojmenování odchylující se od názvosloví českých liturgických knih bylo zvoleno z důvodů místa, aby se to i na malých displejích vešlo na jeden řádek. V tom případě navrhuji "invitatorium".

Dále jsem v tomtéž souboru narazil na slovakismus "Co je nové". Přirozeněji český ekvivalent je "Co je nového", popř. "Novinky", "Nově přidáno" apod.
