### ISSUE TITLE
Regression: Too small fonts on Android 2.3

### ISSUE THREAD

**Issue by n9** [breviar-sk/Liturgia-hodin-online#3]
Not sure when it exactly happened. However, the current version on Google Play, renders fonts too small on Android 2.3. Even using the large fonts, does not help (text is still small). Do you have an apk of the previous release which I could test?

**Comment by breviar-sk** [comment]
The last supported version for Android < 4 is 1.14.6. All APKs of previous versions are here: https://lh.kbs.sk/download/main.htm#android

You can change font size simple by two-fingers "enlarge" gesture.

**Comment by n9** [comment]
Ok, thank you. I've solved the problem with the "enlarge" gesture.
