### ISSUE TITLE
Chyba v textoch - opakujúci sa text [LA]

### ISSUE THREAD

**Issue by vlckoadam** [breviar-sk/Liturgia-hodin-online#9]
V Posv. čítaní pre Veľký piatok sa v texte druhého čítania po skončení 2. odseku (_Occídite, inquit Moyses, ... multo magis se súbtrahit_) ten istý odsek znova opakuje.

**Comment by breviar-sk** [comment]
Ďakujem za upozornenie. Chyby v textoch odporúčame reportovať priamo e-mailom na videky@breviar.sk, najmä kvôli tomu, že kvôli autorským právam NIE SÚ HTML texty súčasťou pravidelného nočného publikovania zmien v kódoch Android aplikácie. Chyba bude opravená v najbližšej aktualizácii; na webe (breviar.sk/la) v najbližších hodinách.
